apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-cd-cert
  namespace: istio-system # istio 설치경로
spec:
  secretName: argo-cd-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: argo-cd.ops.cluster.yanychoi.com
  dnsNames:
  - argo-cd.ops.cluster.yanychoi.com
---
#Gateway
kind: Gateway
apiVersion: networking.istio.io/v1beta1
metadata:
  name: argo-cd-gw
  namespace: istio-system
spec:
  servers:
    - hosts:
        - argo-cd.ops.cluster.yanychoi.com
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        credentialName: argo-cd-tls
        mode: SIMPLE
    - hosts:
        - argo-cd.ops.cluster.yanychoi.com
      port:
        name: http
        number: 80
        protocol: HTTP
  selector:
    app: istio-ingressgateway
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: argo-cd-vs
  namespace: argo-cd
spec:
  hosts:
  - argo-cd.ops.cluster.yanychoi.com
  gateways:
  - argo-cd-gw
  - mesh
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: argo-cd-argocd-server