apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd-apps
  namespace: argo-cd
spec:
  project: default

  source:
    repoURL: https://github.com/yany-ops/k8s-lab.git
    targetRevision: main
    path: kubernetes/apps

  destination:
    namespace: argo-cd
    server: https://kubernetes.default.svc
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true