apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argo-cd
spec:
  project: default
  sources:
  - repoURL: https://github.com/yany-ops/k8s-lab.git
    targetRevision: main
    ref: REPO
    path: kubernetes/charts/argo-cd/patches
  - repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: "7.6.8"
    helm:
      valueFiles:
      - $REPO/kubernetes/charts/argo-cd/values.yaml
  destination:
    namespace: argo-cd
    server: https://kubernetes.default.svc
