apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argo-cd
spec:
  project: default
  sources:
  - repoURL: https://grafana.github.io/helm-charts
    chart: grafana 
    targetRevision: 8.5.2
    helm:
      valueFiles:
      - $REPO/kubernetes/charts/grafana/values.yaml
  - repoURL: https://github.com/yany-ops/k8s-lab.git
    targetRevision: main
    ref: REPO
    path: kubernetes/charts/grafana/patches
  destination:
    namespace: grafana 
    server: https://kubernetes.default.svc

  syncPolicy:
    syncOptions:
    - CreateNamespace=true