apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argo-cd
spec:
  project: default
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 25.27.0
    helm:
      valueFiles:
      - $REPO/kubernetes/charts/prometheus/values.yaml
  - repoURL: https://github.com/yany-ops/k8s-lab.git
    targetRevision: main
    ref: REPO
    path: kubernetes/charts/prometheus/patches
  destination:
    namespace: prometheus
    server: https://kubernetes.default.svc

  syncPolicy:
    syncOptions:
    - CreateNamespace=true